version: '3.1'

services:

  brewi_server:
    build:
      context: .
      target: fastapi
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 8080
    environment:
      DEBUG: 1
    ports:
      - 8080:8080
    volumes:
      - ./app:/code/app:ro
      - ./data:/data
